services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  customers-api:
    build:
      context: ./customers-api
    container_name: customers_api
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./customers-api/.env
    depends_on:
      - db

  orders-api:
    build:
      context: ./orders-api
    container_name: orders_api
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - ./orders-api/.env
    depends_on:
      - db
      - customers-api

  orchestrator:
    build:
      context: ./lambda-orchestrator
    container_name: orchestrator
    ports:
      - "4000:4000"
      - "3003:3003"
    environment:
      CUSTOMERS_API_BASE: http://customers-api:3001
      ORDERS_API_BASE: http://orders-api:3002
      SERVICE_TOKEN: my-secret-token
    depends_on:
      - customers-api
      - orders-api

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
