service: lambda-orchestrator

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  environment:
    CUSTOMERS_API_BASE: ${env:CUSTOMERS_API_BASE}
    ORDERS_API_BASE: ${env:ORDERS_API_BASE}
    SERVICE_TOKEN: ${env:SERVICE_TOKEN}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 3003
    noPrependStageInUrl: true

functions:
  createAndConfirmOrder:
    handler: handler.createAndConfirmOrder
    events:
      - http:
          path: orchestrator/create-and-confirm-order
          method: post