openapi: 3.0.0
info:
  title: Customers API
  version: 1.0.0
  description: API para gestión de clientes

servers:
  - url: http://localhost:3001

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        phone:
          type: string

security:
  - bearerAuth: []

paths:
  /customers:
    post:
      summary: Crear cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Cliente creado
    get:
      summary: Buscar clientes
      parameters:
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: cursor
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Lista de clientes

  /customers/{id}:
    get:
      summary: Obtener cliente por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Cliente encontrado
    put:
      summary: Actualizar cliente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Cliente actualizado
    delete:
      summary: Eliminar cliente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Eliminado

  /internal/customers/{id}:
    get:
      summary: Obtener cliente internamente (uso por otros servicios)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Cliente válido
        '403':
          description: Forbidden (token inválido)
